// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_VZU10223bheO3Y2WjFa1NYWVXASKd0',
    appId: '1:88694391408:web:f5a56be9c4bb33aa1daab5',
    messagingSenderId: '88694391408',
    projectId: 'vikas-project-demo',
    authDomain: 'vikas-project-demo.firebaseapp.com',
    storageBucket: 'vikas-project-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFqFrfKIOvP5ooJ3anN-y9Kp0kXyzJ48',
    appId: '1:88694391408:android:096fd7aa7e79bd201daab5',
    messagingSenderId: '88694391408',
    projectId: 'vikas-project-demo',
    storageBucket: 'vikas-project-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLEHzBzOIoeW0x8CZq2PGcoz2tMbzcOMw',
    appId: '1:88694391408:ios:e8d5e51bd25a602a1daab5',
    messagingSenderId: '88694391408',
    projectId: 'vikas-project-demo',
    storageBucket: 'vikas-project-demo.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
